# Generated by Django 3.1.5 on 2021-01-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=15)),
                ('metodo', models.CharField(max_length=30)),
                ('observacion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.campana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.persona')),
            ],
        ),
        migrations.AddField(
            model_name='campana',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.persona'),
        ),
    ]
